language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby-head
  - rbx-2.2.7
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    recipients:
      - pewniak747@gmail.com
      - bartosz.kopinski@netguru.pl

